package org.Toty.Administrator.View;

import java.awt.Component;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.ArrayList;
import javafx.scene.control.CheckBox;
import javax.swing.ButtonGroup;
import javax.swing.DefaultCellEditor;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
//import org.Toty.Administrator.View.CustomRenderer.PanelRenderer;
import org.Toty.Commons.Packet;
import org.Toty.Commons.User;

/**
 *
 * @author Shivam Sood
 */
public class MainView extends javax.swing.JFrame {

    private Socket socket;
    private ObjectOutputStream out;
    private ObjectInputStream in;
    
    public MainView(Socket socket,ObjectInputStream in,ObjectOutputStream out,String username,ArrayList<User> allUsers) {
        this.socket=socket;
        initComponents();
        usernameLabel.setText(new String(username));
        this.out=out;
        this.in=in;
        DefaultTableModel table=(DefaultTableModel)usersTable.getModel();
        usersTable.getColumn((Object)"Actions").setCellRenderer(new PanelRenderer());
        usersTable.getColumn((Object)"Actions").setCellEditor(new PanelEditor(new JCheckBox()));
        for(User user:allUsers){
            //ButtonGroup group=new ButtonGroup();
            //group.add(new JButton("."+File.pathSeparator+"images"+File.pathSeparator+"check.png"));
            //group.add(new JButton("."+File.pathSeparator+"images"+File.pathSeparator+"check.png"));
            Object[] tempUserString={user.getUsername(),user.getAttribute("nationality"),
                user.getAttribute("role"),user.getAttribute("team"),user.getAttribute("branch"),user};
            table.addRow(tempUserString);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        usersTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrator Login");

        jPanel1.setPreferredSize(new java.awt.Dimension(953, 545));

        usernameLabel.setText("Insert admin name here");

        logoutButton.setText("Logout");

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        usersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Nationality", "Role", "Team", "Branch", "Actions"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        usersTable.setRowHeight(40);
        jScrollPane2.setViewportView(usersTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 852, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jTabbedPane1.addTab("User Requests", jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(usernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutButton)
                    .addComponent(usernameLabel))
                .addGap(5, 5, 5)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("User Requests");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void finalize(){
        try{
            socket.close();
        }catch(IOException e){
            e.printStackTrace();
        }
    }
    
    class PanelRenderer extends JPanel implements TableCellRenderer {
    
        public PanelRenderer(){
            setOpaque(true);
            init();
        }
        // getClass().getResource("/org/Toty/Administrator/View/images/check.png")
        private void init(){
            setLayout(new FlowLayout(FlowLayout.CENTER,0,0));
            add(new JButton(new ImageIcon(getClass().getResource("/org/Toty/Administrator/View/images/check.png"))));
            add(new JButton(new ImageIcon(getClass().getResource("/org/Toty/Administrator/View/images/delete.png"))));
        }
    
        public Component getTableCellRendererComponent(JTable table,Object value,boolean isSelected,
                                                         boolean hasFocus,int row,int column){
            if ( isSelected ){
                setForeground( table.getSelectionForeground() );
                setBackground( table.getSelectionBackground() );
            }else{
                setForeground( table.getForeground() );
                setBackground( UIManager.getColor( "Button.background" ) );
            }
            return this;
        }
    }
    
    class PanelEditor extends DefaultCellEditor{
        protected JPanel panel;
        protected JButton button1,button2;
    
        public PanelEditor(JCheckBox checkBox){
            super(checkBox);
            panel=new JPanel(new FlowLayout(FlowLayout.CENTER,5,0));
            button1=new JButton("1");
            button1.setOpaque(true);
            button1.setActionCommand("Action 1");
            button1.addActionListener(new ActionListener(){
                public void actionPerformed(ActionEvent e){
                    JOptionPane.showMessageDialog( button1, button1.getText()+": Ouch!" );
                    fireEditingStopped();
                }
            });
            button2=new JButton("2");
            button2.setOpaque(true);
            button2.addActionListener(new ActionListener(){
                public void actionPerformed( ActionEvent e ) {
                    JOptionPane.showMessageDialog( button2, button2.getText()+ ": Ouch!" );
                    fireEditingStopped();
                }
            });
            panel.add( button1 );
            panel.add( button2 );
        }
        @Override
        public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row, int column){
            if(isSelected){
                button1.setForeground(table.getSelectionForeground());
                button1.setBackground(table.getSelectionBackground());
            }
            else{
                button1.setForeground(table.getForeground());
                button1.setBackground(table.getBackground());
            }
            return panel;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTable usersTable;
    // End of variables declaration//GEN-END:variables
}
