package org.Toty.Administrator.View;

import java.awt.Component;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.ArrayList;
import javax.swing.DefaultCellEditor;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import org.Toty.Commons.Packet;
import org.Toty.Commons.User;
import org.Toty.Server.Service.SignUpApproveService;
import org.Toty.Server.Service.SignUpRequestService;

/**
 *
 * @author Shivam Sood
 */
public class MainView extends javax.swing.JFrame {

    private Socket socket;
    private ObjectOutputStream out;
    private ObjectInputStream in;
    private ArrayList<User> allUsers;
    private DefaultTableModel table;
    private String adminname;
    
    public MainView(Socket socket,ObjectInputStream in,ObjectOutputStream out,String adminname) {
        this.out=out;
        this.in=in;
        this.socket=socket;
        initComponents();
        //set adminname label
        usernameLabel.setText(this.adminname=new String(adminname));
        //set user table actions
        usersTable.getColumn("Actions").setCellRenderer(new PanelRenderer());
        usersTable.getColumn("Actions").setCellEditor(new PanelEditor(new JCheckBox()));
        table=(DefaultTableModel)usersTable.getModel();
        setUserRequestsTable();
    }
    
    public void setUserRequestsTable(){
        this.allUsers=getAllUsers();
        while(table.getRowCount()>0){
            table.removeRow(0);
        }
        for(User user:allUsers){
            Object[] tempUserString={user.getUsername(),user.getAttribute("nationality"),
                user.getAttribute("role"),user.getAttribute("team"),user.getAttribute("branch"),null};
            table.addRow(tempUserString);
        }
    }
    
    public ArrayList<User> getAllUsers(){
        try{
            out.writeObject(new Packet(104));
            Packet packet=(Packet)in.readObject();
            return (ArrayList<User>)packet.getObject();
        }catch(IOException e){
            e.printStackTrace();
        }catch(ClassNotFoundException e){
            e.printStackTrace();
        }
        return new ArrayList<User>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        usersTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        logoutButton = new javax.swing.JButton();
        usernameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrator Login");
        setPreferredSize(new java.awt.Dimension(900, 503));
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(953, 545));

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        usersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Nationality", "Role", "Team", "Branch", "Actions"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        usersTable.setRowHeight(45);
        jScrollPane2.setViewportView(usersTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("User Requests", jPanel2);

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        usernameLabel.setText("Insert admin name here");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutButton)
                    .addComponent(usernameLabel)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("User Requests");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        Packet packet=new Packet(909,adminname);
        try{
            out.writeObject(packet);
            System.out.println("logout Successful");
        }
        catch(IOException e){
            e.printStackTrace();
        }
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_logoutButtonActionPerformed
    
    public void finalize(){
        try{
            in.close();
            out.close();
            socket.close();
        }catch(IOException e){
            e.printStackTrace();
        }
    }
    
    class PanelRenderer extends JPanel implements TableCellRenderer {
    
        public PanelRenderer(){
            setOpaque(true);
            init();
        }
        
        private void init(){
            setLayout(new FlowLayout(FlowLayout.CENTER,0,0));
            add(new JButton(new ImageIcon(getClass().getResource("/Administrator/check.png"))));
            add(new JButton(new ImageIcon(getClass().getResource("/Administrator/delete.png"))));
            pack();
        }
        
        @Override
        public Component getTableCellRendererComponent(JTable table,Object value,boolean isSelected,
                                        boolean hasFocus,int row,int column){
            if ( isSelected ){
                setForeground( table.getSelectionForeground() );
                setBackground( table.getSelectionBackground() );
            }else{
                setForeground( table.getForeground() );
                setBackground( UIManager.getColor( "Button.background" ) );
            }
            return this;
        }
    }
    
    class PanelEditor extends DefaultCellEditor{
        protected JPanel panel;
        protected JButton button1,button2;
        protected int row,column;
        public PanelEditor(JCheckBox checkBox){
            super(checkBox);
            panel=new JPanel(new FlowLayout(FlowLayout.CENTER,0,0));
            button1=new JButton(new ImageIcon(getClass().getResource("/Administrator/check.png")));
            button1.setOpaque(true);
            //button1.setActionCommand("Action 1");
            button2=new JButton(new ImageIcon(getClass().getResource("/Administrator/delete.png")));
            button2.setOpaque(true);
            //button2.setActionCommand("Action 2");
            panel.add( button1 );
            panel.add( button2 );
            button1.addActionListener(new ActionListener(){
                public void actionPerformed(ActionEvent e){
                    //fireEditingStopped();
                    //System.out.println("Checked Row: " + row + " Column: " + column);
                    System.out.println("Button 1 pressed");
                    Packet requestPacket=new Packet(6,allUsers.get(row));//user request to added to login
                    try {
                        out.writeObject(requestPacket);
                        out.flush();
                        Packet responsePacket = (Packet) in.readObject();
                        /*
                        if (responsePacket.getCode() == 505) {
                            if ((Boolean) responsePacket.getObject()) {
                                allUsers.remove(row);
                                table.removeRow(row);
                            }
                        }
                        System.out.println("Button 1 press completed");
                        */
                        System.out.println("Button 1 press completed");
                        setUserRequestsTable();
                    } catch (IOException exception) {
                        exception.printStackTrace();
                    } catch (ClassNotFoundException exception){
                        exception.printStackTrace();
                    }
                }
            });
            button2.addActionListener(new ActionListener(){
                public void actionPerformed( ActionEvent e ) {
                    //fireEditingStopped();
                    System.out.println("Button 2 pressed");
                    Packet requestPacket=new Packet(5,allUsers.get(row).getUsername());
                    try{
                        out.writeObject(requestPacket);
                        out.flush();
                        Packet responsePacket=(Packet)in.readObject();
                        /*
                        if(responsePacket.getCode()==504){
                            if((Boolean)responsePacket.getObject()){
                                allUsers.remove(row);
                                table.removeRow(row);
                            }
                        }
                        */
                        System.out.println("Button 2 press completed");
                        setUserRequestsTable();
                    }catch(IOException exception){
                        exception.printStackTrace();
                    }catch(ClassNotFoundException exception2){
                        exception2.printStackTrace();
                    }
                }
            });
        }
        
        @Override
        public Component getTableCellEditorComponent(JTable jTable, Object value, boolean isSelected, int row, int column){
            /*
            if(isSelected){
                button1.setForeground(jTable.getSelectionForeground());
                button1.setBackground(jTable.getSelectionBackground());
                button2.setForeground(jTable.getSelectionForeground());
                button2.setBackground(jTable.getSelectionBackground());
            }
            else{
                button1.setForeground(jTable.getForeground());
                button1.setBackground(jTable.getBackground());
                button2.setForeground(jTable.getForeground());
                button2.setBackground(jTable.getBackground());
            }
            */
            this.row=row;
            this.column=column;
            System.out.println("getTableCellEditoComponent: "+row+" "+column);
            //System.out.println(allUsers);
            return panel;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTable usersTable;
    // End of variables declaration//GEN-END:variables
}
